version: "3.9"
services:
  # MYSQL Database (igual que en dev)
  database:
    image: mysql:8.0.35
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - wp_network

  # WORDPRESS (modificado para producción)
  wordpress:
    depends_on:
      - database
    image: custom-wordpress:latest # Imagen personalizada
    # Puerto estándar HTTP
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - wp_uploads:/var/www/html/wp-content/uploads # Uploads en volumen
      # Archivos de configuración
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./.htaccess:/var/www/html/.htaccess
      # Archivos de configuración de PHP
      - ./wp-content/plugins:/var/www/html/wp-content/plugins # Plugins versionados
      - ./wp-content/themes:/var/www/html/wp-content/themes # Temas versionados
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DEBUG: "0" # Debug desactivado
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"
    networks:
      - wp_network

networks:
  wp_network:

volumes:
  db_data:
  wp_uploads: # Volumen para uploads en producción
